Upgrade protobuf mapper to work wit NATS
siddhi-io/siddhi-map-protobuf pull request #7
Opened 2019-10-23 12:41 UTC by sahandilshan

## Purpose
Resolve issue in NATS(Support protobuf in source and sink #23)

## Goals
> Receive/Publish protobuf message from/to byte array.

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

2019-10-23 12:48 UTC, pcnfernando requested changes

2019-10-23 12:48 UTC, pcnfernando commented on component/src/main/java/io/siddhi/extension/map/protobuf/sinkmapper/ProtobufSinkMapper.java
> +            if (sinkType.startsWith(GrpcConstants.GRPC_PROTOCOL_NAME)) {
Do a uppercase/lowercase and then check startsWith. Else, it will be case sensitive

2019-10-23 12:48 UTC, pcnfernando commented on component/src/main/java/io/siddhi/extension/map/protobuf/sourcemapper/ProtobufSourceMapper.java
> +                        "protobuf" +
Merge the line below to a single line

2019-10-23 12:48 UTC, pcnfernando commented on component/src/main/java/io/siddhi/extension/map/protobuf/sourcemapper/ProtobufSourceMapper.java
> +                throw new SiddhiAppRuntimeException(siddhiAppName + ":" + streamID + " error while creating the " +
Add more context to the error message(which sink,map...)

2019-10-23 13:58 UTC, pcnfernando approved these changes

2019-10-23 13:58 UTC, merged

2019-10-24 07:11 UTC, BuddhiWathsala commented
This PR solved https://github.com/siddhi-io/siddhi-io-nats/issues/23 issue at the protobuf level.